### PR TITLE
Task-3.6 - Position Movement Today Chart

### PR DESCRIPTION
**Pull request by asprincean**
This is a draft

### CODE REVIEW

**Review by Rinhammar — APPROVED** [review]

**Review by michaelcairney — COMMENTED** [review]
image
Looks like there is a gap for me

**Comment by asprincean** [comment]
> image Looks like there is a gap for me - same for you?

The left chart should have the same height as this chart

**Comment by Rinhammar** [comment]
> > image Looks like there is a gap for me - same for you?
> 
> The left chart should have the same height as this chart

It will have the same height and then this gap won't be there.

**Review by michaelcairney — APPROVED** [review]
I see thankyou for clarifying 🙂

**Pull request merged**
