### PR TITLE
fixed scatterplot graph

### PR DESCRIPTION
**Pull request by ckp8**

### CODE REVIEW

**Review by asprincean — COMMENTED** [review]
Nice work! Just some comments:
1. Legend 
    - next to the labels are squares, but in the figma design are rectangles;
    - colors of the labels are a bit different;
2. Chart
    - is slightly to the right (see the space between chart and the container, on the left)
    - the color of the axes and ticks labels is not matching the figma design

**Review by Rinhammar — CHANGES_REQUESTED** [review]
I agree with the points @asprincean made. I also want to add that the dots shouldn't have a white outline around them. This can be fixed by removing:
.attr("stroke", "white")
.attr("stroke-width", 1)
.attr("stroke-opacity", 1) in scatterplot.jsx

**Comment by ckp8** [comment]
> Nice work! Just some comments:
> 
> 1. Legend
>    
>    * next to the labels are squares, but in the figma design are rectangles;
>    * colors of the labels are a bit different;
> 2. Chart
>    
>    * is slightly to the right (see the space between chart and the container, on the left)
>    * the color of the axes and ticks labels is not matching the figma design

the colours are from the figma design

**Comment by asprincean** [comment]
> > Nice work! Just some comments:
> > 
> > 1. Legend
> >    
> >    * next to the labels are squares, but in the figma design are rectangles;
> >    * colors of the labels are a bit different;
> > 2. Chart
> >    
> >    * is slightly to the right (see the space between chart and the container, on the left)
> >    * the color of the axes and ticks labels is not matching the figma design
> 
> the colours are from the figma design

Sorry, they seemed a little different to me. But you are right.

**Review by Rinhammar — CHANGES_REQUESTED** [review]
I have a few points.

1. The values on the y- and x-axis don't match the design. 
2. You have the wrong amount of clusters. Should be 5, not 6. The clusters also have the wrong colours.
3. The margin on the left doesn't match the design. The chart should start way closer to the left. 

image

For future, match the design. If it doesn't look the same as the design, change it. If you don't know how to, ask. We are here to help.

**Review by Rinhammar — CHANGES_REQUESTED** [review]
1. The values on the x- and y-axis still don't match the design. 
2. Also both the x- and y-axis shouldn't have the ticks. 
3. The values on the x-axis shouldn't be tilted. 
4. Please check that the colours of the values and the lines match the design too. The lines should be a darker gray for example.

Please see the design below and match those values. I know you said it might change when we get the Qlik data etc, but it's still important to be able to match a design. It might be shown to clients/business people in this state.

image

**Review by asprincean — APPROVED** [review]

**Review by Rinhammar — APPROVED** [review]

**Pull request merged**
